onst db = require('./models/database');

const postos = [
    { nome: 'Airton Monte', regional: 'I' },
    { nome: 'Carlos Ribeiro', regional: 'I' },
    { nome: 'Casemiro Filho', regional: 'I' },
    { nome: 'Chico da Silva', regional: 'I' },
    { nome: 'Fernando Façanha', regional: 'I' },
    { nome: 'Floresta (em reforma)', regional: 'I' },
    { nome: 'Guiomar Arruda', regional: 'I' },
    { nome: 'João Madeiros', regional: 'I' },
    { nome: 'Lineu Jucá', regional: 'I' },
    { nome: 'Maria Aparecida', regional: 'I' },
    { nome: 'Maria Cirino Souza', regional: 'I' },
    { nome: 'Paulo de Melo 4 Varas', regional: 'I' },
    { nome: 'Rebouças Macambira', regional: 'I' },
    { nome: 'Virgílio Távora', regional: 'I' },
    { nome: 'Dr. Tito', regional: 'I' },
    { nome: 'Irmã Hercília Aragão (em reforma)', regional: 'I' },
    { nome: 'Miriam Porto Mota', regional: 'I' },
    { nome: 'Odorico de Morais', regional: 'I' },
    { nome: 'Paulo Marcelo', regional: 'I' },
    { nome: 'Pio XII', regional: 'I' },
    { nome: 'Rigoberto Romero (em reforma)', regional: 'I' },
    { nome: 'Sandra Maria Faustino (em reforma)', regional: 'I' },
    { nome: 'Liduína Maria Araújo', regional: 'I' },
    { nome: 'Fátima Maria Quezado Fernandes', regional: 'I' },
    { nome: 'Anastácio Magalhães (em reforma)', regional: 'III' },
    { nome: 'César Cals de Oliveira Filho', regional: 'III' },
    { nome: 'Clodoaldo Pinto', regional: 'III' },
    { nome: 'Eliézer Studart', regional: 'III' },
    { nome: 'Fernandes Távora', regional: 'III' },
    { nome: 'Francisco Pereira de Almeida', regional: 'III' },
    { nome: 'George Benevides', regional: 'III' },
    { nome: 'Hermínia Leitão', regional: 'III' },
    { nome: 'Humberto Bezerra', regional: 'III' },
    { nome: 'Ivana Paes (em reforma)', regional: 'III' },
    { nome: 'Cícera Carla Almeida - João XXIII', regional: 'III' },
    { nome: 'Lícinio Nunes de Miranda', regional: 'III' },
    { nome: 'Luís Recamonde Capelo', regional: 'III' },
    { nome: 'Mariusa Silva de Sousa', regional: 'III' },
    { nome: 'Meton de Alencar', regional: 'III' },
    { nome: 'Santa Liduina', regional: 'III' },
    { nome: 'José Sobreira de Amorim', regional: 'III' },
    { nome: 'Waldemar Alcântara', regional: 'III' },
    { nome: 'Gilmário Mourão Teixeira', regional: 'III' },
    { nome: 'Fábio Martins de Lima', regional: 'III' },
    { nome: 'Abel Pinto (em reforma)', regional: 'IV' },
    { nome: 'Dom Aloiso Lorscheider', regional: 'IV' },
    { nome: 'Fco. Monteiro', regional: 'IV' },
    { nome: 'Gothardo Peixoto', regional: 'IV' },
    { nome: 'F. Lima', regional: 'IV' },
    { nome: 'Gutemberg Braun', regional: 'IV' },
    { nome: 'José Valdevino Carvalho', regional: 'IV' },
    { nome: 'Luis Albuquerque Mendes', regional: 'IV' },
    { nome: 'Luis Costa', regional: 'IV' },
    { nome: 'Ocelo Pinheiro', regional: 'IV' },
    { nome: 'Oliveira Pombo', regional: 'IV' },
    { nome: 'Antônio Ciríaco de Holanda', regional: 'IV' },
    { nome: 'Roberto Bruno', regional: 'IV' },
    { nome: 'Turbay Barreira', regional: 'IV' },
    { nome: 'Dom José Bezerra Coutinho', regional: 'IV' },
    { nome: 'Posto Dr. Raimundo Pontes Filho', regional: 'IV' },
    { nome: 'Abner Cavalcante Brasil', regional: 'V' },
    { nome: 'Argeu Herbster', regional: 'V' },
    { nome: 'Dom Lustosa', regional: 'V' },
    { nome: 'Fco. Edmilson Pinheiro', regional: 'V' },
    { nome: 'Fernando Diógenes', regional: 'V' },
    { nome: 'Graciliano Muniz', regional: 'V' },
    { nome: 'Guarany Mont'alverne', regional: 'V' },
    { nome: 'Dr. João Barbosa', regional: 'V' },
    { nome: 'Pires de Paula Pessoa', regional: 'V' },
    { nome: 'João Elísio Holanda', regional: 'V' },
    { nome: 'José Galba de Araújo', regional: 'V' },
    { nome: 'José Paracampos', regional: 'V' },
    { nome: 'José Walter', regional: 'V' },
    { nome: 'Jurandir Picanço', regional: 'V' },
    { nome: 'Luciano Torres de Melo', regional: 'V' },
    { nome: 'Luiza Távora', regional: 'V' },
    { nome: 'Maciel de Brito (em reforma)', regional: 'V' },
    { nome: 'Parque São José', regional: 'V' },
    { nome: 'Pedro Celestino', regional: 'V' },
    { nome: 'Dr. Pontes Neto', regional: 'V' },
    { nome: 'Regina Maria da Silva', regional: 'V' },
    { nome: 'Severino Régis Jucá', regional: 'V' },
    { nome: 'Ronaldo Albuquerque Siqueira', regional: 'V' },
    { nome: 'Viviane Benevides (em reforma)', regional: 'V' },
    { nome: 'Doutor Henrique Mota Neto', regional: 'V' },
    { nome: 'Zélia Correia (em reforma)', regional: 'V' },
    { nome: 'João Machado dos Santos', regional: 'V' },
    { nome: 'Fernando Uchôa Costa', regional: 'V' },
    { nome: 'Pedro Uchoa', regional: 'V' },
    { nome: 'Francisco Tailson Pinheiro', regional: 'V' },
    { nome: 'Agueda Xerez Cunha', regional: 'V' },
    { nome: 'Rita Maria Lemos Coelho', regional: 'V' },
    { nome: 'Alarico Leite', regional: 'VI' },
    { nome: 'Anísio Teixeira', regional: 'VI' },
    { nome: 'César Cals de Oliveira', regional: 'VI' },
    { nome: 'Edilmar Norões', regional: 'VI' },
    { nome: 'Edmar Fujita', regional: 'VI' },
    { nome: 'Evandro Ayres de Moura', regional: 'VI' },
    { nome: 'Dr. Sampaio Pompeu Vasconcelos', regional: 'VI' },
    { nome: 'Sítio São João', regional: 'VI' },
    { nome: 'Terezinha Parente', regional: 'VI' },
    { nome: 'Vicentina Campos', regional: 'VI' },
    { nome: 'Waldo Pessoa', regional: 'VI' },
    { nome: 'Doutor Sergio Gomes de Matos', regional: 'VI' },
    { nome: 'Josafá Gomes da Silva', regional: 'VI' },
    { nome: 'Márcia Maria Mesquita Veloso', regional: 'VI' },
    { nome: 'Padre Alberto Trombini', regional: 'VI' },
];

const medicamentos = [
    { nome: 'Aciclovir 200 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Ácido acetilsalicílico 100 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Ácido fólico 5 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Albendazol 40 mg/ml + dosador, suspensão oral. Frasco 10 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Albendazol 400 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Amiodarona (cloridrato) 200 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Amoxicilina + clavulanato de potássio 500 mg + 125 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Amoxicilina + clavulanato de potássio 50 mg/ml + 12,5 mg/ml + dosador, pó para suspensão oral. Frasco 100 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Amoxicilina 50 mg/ml + dosador, pó para suspensão oral. Frasco 150 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Amoxicilina 500 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Anlodipino (besilato) 5 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Atenolol 50 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Azitromicina 40 mg/ml suspensão oral 600 mg. Suspensão oral', disponivel: 1, posto_id: 1 },
    { nome: 'Azitromicina 500 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Beclometasona (dipropionato) 200 mcg/dose solução para inalação oral, 200 doses. Spray', disponivel: 1, posto_id: 1 },
    { nome: 'Beclometasona (dipropionato) 50 mcg/dose solução para inalação oral, 200 doses. Spray', disponivel: 1, posto_id: 1 },
    { nome: 'Benzilpenicilina benzatina 1.200.000 ui pó para suspensão injetável + diluente', disponivel: 1, posto_id: 1 },
    { nome: 'Carbonato de cálcio 600 mg + colicalciferol 400 ui', disponivel: 1, posto_id: 1 },
    { nome: 'Carvedilol 25 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Carvedilol 6,25 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Cefalexina 50 mg/ml + dosador, suspensão oral. Frasco 100 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Cefalexina 500 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Ceftriaxona 500 mg pó para solução injetável + diluente (intramuscular)', disponivel: 1, posto_id: 1 },
    { nome: 'Ciprofloxacino (cloridrato) 500 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Cloreto de sódio 0,9% solução injetável, sistema fechado frasco 500 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Dexametasona 0,1% creme dermatológico. Bisnaga 10 g', disponivel: 1, posto_id: 1 },
    { nome: 'Dipirona (sódica) 500 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Dipirona 500 mg/ml, solução injetável. Ampola 2 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Dipirona 500 mg/ml – solução oral (gotas)', disponivel: 1, posto_id: 1 },
    { nome: 'Doxazosina (mesilato) 2 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Enalapril (maleato) 20 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Enalapril (maleato) 10 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Espironolactona 25 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Finasterida 5 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Fluconazol 150 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Fosfomicina trometamol 5.631 g / 8 g', disponivel: 1, posto_id: 1 },
    { nome: 'Furosemida 40 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Glibenclamida 5 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Gliclazida 60 mg. Comprimido de liberação prolongada.', disponivel: 1, posto_id: 1 },
    { nome: 'Hidroclorotiazida 25 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Ibuprofeno 50 mg/ml, suspensão oral. Frasco 50 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Ibuprofeno 600 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Isossorbida (mononitrato) 40 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Levodopa 100 mg + benserazida 25 mg comprimido (birranhurado)', disponivel: 1, posto_id: 1 },
    { nome: 'Levodopa 100 mg + benserazida 25 mg (hbs)', disponivel: 1, posto_id: 1 },
    { nome: 'Levodopa 200 mg + benserazida 50 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Levotiroxina (sódica), 25 mcg', disponivel: 1, posto_id: 1 },
    { nome: 'Levotiroxina 100 mcg. Comprimido', disponivel: 1, posto_id: 1 },
    { nome: 'Lidocaína (cloridrato) 20 mg/g (2)% gel. Bisnaga 30 g', disponivel: 1, posto_id: 1 },
    { nome: 'Loratadina 1 mg/ml - 100 ml. Xarope', disponivel: 1, posto_id: 1 },
    { nome: 'Loratadina 10 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Losartana 50 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Metformina 500 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Metildopa 250 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Metoclopramida (cloridrato), 4 mg/ml – 10 ml. Solução oral', disponivel: 1, posto_id: 1 },
    { nome: 'Metronidazol 100 mcg/g creme vaginal bisnaga 50 g + aplicador', disponivel: 1, posto_id: 1 },
    { nome: 'Metronidazol 250 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Miconazol (nitrato) 20 mg/g (2%) creme dermatológico. Bisnaga 28 g', disponivel: 1, posto_id: 1 },
    { nome: 'Miconazol 2% creme vaginal + aplicador – 80 g', disponivel: 1, posto_id: 1 },
    { nome: 'Nistatina 100.000 ui/ml – 50 ml. Suspensão oral', disponivel: 1, posto_id: 1 },
    { nome: 'Nitrofurantoína 100 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Óleo mineral. Frasco 100 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Omeprazol 20 mg. Cápsula', disponivel: 1, posto_id: 1 },
    { nome: 'Paracetamol 200 mg/ml, solução oral. Frasco-gotas 15 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Paracetamol 500 mg. Comprimido', disponivel: 1, posto_id: 1 },
    { nome: 'Permetrina 1% loção. Frasco 60ml', disponivel: 1, posto_id: 1 },
    { nome: 'Permetrina 50 mg/g (5%) loção. Frasco 60 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Prednisolona (fosfáto sódico) - 3 mg/ml - solução oral', disponivel: 1, posto_id: 1 },
    { nome: 'Prednisona 20 mg. Comprimido', disponivel: 1, posto_id: 1 },
    { nome: 'Prednisona 5 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Propranolol (cloridrato) 40 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Sais p/ reidratação oral 27,9 g - pó para solução oral', disponivel: 1, posto_id: 1 },
    { nome: 'Salbutamol (sulfato) 100 mcg/dose - aerossol oral. Frasco spray 200 doses', disponivel: 1, posto_id: 1 },
    { nome: 'Sinvastatina 20 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Sulfametoxazol + trimetoprima 40 mg/ml + 8 mg/ml, suspensão oral. Frasco 100 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Sulfametoxazol + trimetoprima 400 + 80 mg', disponivel: 1, posto_id: 1 },
    { nome: 'Sulfato ferroso 25 mg/ml + conta gotas, solução oral. Frasco 30 ml', disponivel: 1, posto_id: 1 },
    { nome: 'Sulfato ferroso 40 mg. Comprimido', disponivel: 1, posto_id: 1 },
    { nome: 'Timolol maleato 0,5% - 5 ml. Frasco gotas', disponivel: 1, posto_id: 1 },
    { nome: 'Varfarina, comprimido contendo 5 mg', disponivel: 1, posto_id: 1 },
];

db.serialize(() => {
    postos.forEach((posto) => {
        db.run(
            'INSERT INTO postos (nome, regional) VALUES (?, ?)',
            [posto.nome, posto.regional],
            (err) => {
                if (err) console.error('Erro ao inserir posto:', err);
                else console.log(`Posto "${posto.nome}" inserido com sucesso!`);
            }
        );
    });

    medicamentos.forEach((medicamento) => {
        db.run(
            'INSERT INTO medicamentos (nome, disponivel, posto_id) VALUES (?, ?, ?)',
            [medicamento.nome, medicamento.disponivel, medicamento.posto_id],
            (err) => {
                if (err) console.error('Erro ao inserir medicamento:', err);
                else console.log(`Medicamento "${medicamento.nome}" inserido com sucesso!`);
            }
        );
    });
});

console.log('Banco de dados populado com sucesso!');
```